version: "3.9"
services:
  lewi-web-api:
    container_name: lewi-web-api
    build: ./web-api
    expose:
      - 8390
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - backend-network
    
  lewi-web-service:
    container_name: lewi-web-service
    build: ./web-service
    ports:
      - 8390:8390
    depends_on:
      - lewi-web-api
    networks:
      - backend-network
  
  lewi-web-front:
    container_name: lewi-web-front
    build: ./web-front
    ports:
      - 80:80
    environment: 
      - API_URL=${API_URL}
    networks:
      - backend-network
  
  lewi-mysql:
    container_name: lewi-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes: 
      - ${MYSQL_PATH}:/var/lib/mysql
    networks:
      - backend-network
    hostname: ${MYSQL_HOST}
  
networks: 
  backend-network: